cesium-ml/baselayer

- app/models.py
Now returns a proper ORM model instead of an `sa.Table` object.
> Replace `join_table` with `join_model`

- conf/supervisor/app.conf
- conf/supervisor/debug.conf
- conf/supervisor/supervisor.conf
- conf/supervisor/testing.conf
- tools/supervisor_status.py
- tools/watch_logs.py
Previously, we had separate configurations for the standard/debug
versions of each service.  Now, the $FLAGS environment variable is
sent to the services that require options instead.
Supervisor cannot handle non-existent environment variables, so
you *have* to specify FLAGS, even if it is empty.  This is addressed
in the Makefile, by modifying the supervisord script to be `FLAGS=$(FLAGS)
supervisord` instead, so that it reuses any existing FLAGS definition,
or defines it as empty otherwise.
This change will necessitate modifications to Cesium and others
relying on baselayer.
> Refactor supervisor to receive flags

- app/app_server.py
- app/handlers/base.py
- app/psa.py
- conf/supervisor/supervisor.conf
- config.yaml.example
This prevents problems with a user being created in single-user
mode (no Python Social Auth entry), and the same username then logging
in later under multi-user mode, creating a new profile.
> Always use multi-user mode

- app/__init__.py
- app/app_server.py
- app/config.py
- app/env.py
- services/app.py
- tools/db_init.py
- tools/env_summary.py
- The environment (command line flags) determine which configuration
to load.  Everywhere where the configuration is loaded, the
environment should be examined as well.  As such, these two
operations have been combined.
- Factoring out the config+env loader allows us to print the
environment after launching the server, so that users know which URL
to connect to, e.g.
- The refactor also simplifies `services/app` (which should be fairly
minimal), and moves some of its logic to `baselayer/app/app_server`
instead.
> Refactor config loading into (environment + config) loading

- app/psa.py
- conf/nginx.conf
- config.yaml.example
Now, we no longer have to provide the server path in the configuration
file, and that authentication will work both when accessing the server
via localhost or a public DNS name.
1. Configure nginx to pass requests for `/fakeoauth2/*` to the
microservice, running on port 63000.  This means the authentication
URLs becomes `/fakeoauth2/{auth,token}`.
2. Python Social Auth's OAuth2 backends all require absolute redirect
URLs.  Fortunately, the backend Strategy (Tornado, in our case),
provide a method, `absolute_path`, to convert relative to absolute
paths.
> Let Fake OAuth2 self-discover the server path

- app/psa.py
- conf/nginx.conf.template
Previously, we tried to verify OAuth2 credentials by posting to the
same URL as used by the browser + `/fakeoauth2/token`.  The token
request is made internally (from the web browser), resulting in
problems when hosting via Docker.
For example, the browser may point to `http://localhost:9000` because
Docker remaps 5000 -> 9000.  But from inside the Docker
container (where the server runs), the FakeOAuth URL remains
`http://localhost:5000/fakeoauth2` (not 9000).
The workaround here is to connect directly to the hosted port of the
service (default 63000).
> Correctly route OAuth2 requests to FakeOAuth2 server

- tools/test_frontend.py
This is also a test of the dependent build server; hold off on merging.
> Explicitly print exception when test server fails to start

- Makefile
- services/webpack.py
- tools/supervisor_status.py
1. If in production mode, launch webpack only if `bundle.js` is missing.
2. When in debug mode, launch the webpack monitor (changes to .js
files are automatically re-bundled).
Closes #24
> Launch WebPack as required by server mode

- .travis.yml
- app/psa.py
- requirements.txt
The way Python Social Auth gets email addresses from OAuth2 responses
has changed, due to
python-social-auth/social-core@d77d75547b9ada3460a1b6809c8c9ad854f76871
> Fix fake authentication with newer versions of Python Social Auth

- Makefile
- doc/setup.md
This allows FLAGS to be extended from the outside, so you can do, e.g.:
```
FLAGS="--config=foo.yaml" make run
```
We never fully supported this use case before, relying on `config.yaml` to be the default configuration.
> Set FLAGS to config.yaml for all targets

- requirements.txt
- tools/check_app_environment.py
Previously, because supervisord only ran on Python 2, we required the
user to install it separately.  Now that it is available for Python 3,
automatically install it when necessary.
> Install supervisord from pip

- tools/supervisor_status.py
- tools/test_frontend.py
There are various reasons why these occur: the socket doesn't yet exist,
etc.  But we don't really care: we just want to know if the services are
up and running.
> Ignore exceptions raised by supervisor_status

- static/js/MessageHandler.js
- static/js/components/WebSocket.jsx
There is now a singleton `messageHandler` object.  To register a
handler, use `messageHandler.add(handler)`.  The handler should be a
function of the form:
```
(action, payload, dispatch, getState) => { ... }
```
> Refactor MessageHandler

- app/models.py
Previously, if an ID was supplied to `Base.get_if_owned_by` that did not exist, an error was raised. This method should mirror the behavior of `query.get`, which returns `None` instead of erroring in that case. This PR makes `get_if_owned_by` return `None` if no matching ID exists, to match the behavior of `query.get`.
> Have get_if_owned_by return None if no obj w/ ID instead of erroring

- tools/supervisor_status.py
- tools/test_frontend.py
Supervisor 4 introduces an error code on exited services
(https://github.com/Supervisor/supervisor/issues/1223).
The internal function that calls supervisorctl has been modified to
return the output as well as the error code. When the error code is 3,
we now proceed as though the operation was successful (which, typicall,
it was).
> Fix supervisorctl monitoring of micro-services

- app/models.py
I added a column to `models.Base` that keeps track of when any ORM-mapped entity is modified. This will complement the `created_at` field for keeping track of the provenance of objects and data.
> keep track of when db-mapped entities are modified

- app/models.py
Add a reverse index to all join tables so that both (fk1, fk2) and (fk2, fk1) are sargable (i.e., fast queries in either direction)
> add reverse index to join model

- app/handlers/base.py
Currently, the API returns messages of the format:
```
{
"status": "success",
"data": ...
}
```
We would like apps to be able to add their own fields adjacent to
`status` and `data`:
```
{
"status": "success",
"data": ...,
"customfield1": ...,
"customfield2": ...
}
```
Motivated by SkyPortal wanting to return a `version` field.
> Allow baselayer apps to add fields to API JSON returns

- static/js/cookies.js
Soon, Firefox will start rejecting cookies that don't have either
SameSite or Secure set.  See also:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#SameSite_cookies
> Require that browser send cookies only for this site

- tools/fill_conf_values.py
This is necessary for compiled JSX files to pass lint validation
> Add a newline to the end of compiled templates

- app/models.py
- requirements.txt
This PR is a companion to skyportal/skyportal#517 and is a dependency of that PR. 
This PR:
* bumps sqlalchemy to 1.3.7 to make use of `executemany_mode = 'values'` (https://docs.sqlalchemy.org/en/13/dialects/postgresql.html#psycopg2-fast-execution-helpers)
* Sets a global `EXECUTEMANY_PAGESIZE` parameter which determines how many VALUES tuples to bundle into a single insert, I set it to the default of 10k
> use executemany_mode = values

- Makefile
- tools/test_frontend.py
This PR adds a new `Makefile` target, `make test_xml`, to generate a py.test report that can be used to track test flakiness on BuildPulse. `make test_xml` runs `tools/test_frontend.py` with a new `--xml` flag, which tells `test_frontend.py` to pass `--junitxml=../../test-results/junit.xml` to `py.test`.  This stores the test results in a manner that can be read and parsed by BuildPulse.
> Add new makefile target test_xml to generate py.test report for BuildPulse

- app/env.py
Utilities that use `load_env` may also want to add their own command
line arguments.  Having access to the parser allows them to do so.
> Expose parser so utilities can use it

- app/test_util.py
Noticed while playing around with tests that the current CSS- based WebDriverWait utility functions have the incorrect By argument ("By.CSS" should be "By.CSS_SELECTOR").
Source [Selenium documentation](https://selenium-python.readthedocs.io/api.html#locate-elements-by):
> User proper CSS selector for selenium driver utils

- tools/db_init.py
- Before, we did not fail when db already existed.  Now, there is an
explicit check for that.  We also don't try and recreate an existing
database.
- Explain to the user how to create a DB and permissions if our
creation didn't work.  System configurations can be complex, so we
cannot expect to succeed always.
> Make dbinit more robust and provide helpful feedback

- .gitignore
- app/env.py
- config.yaml.defaults
- services/app/app.py
- services/app/supervisor.conf
- services/app/supervisor.conf.template
- services/nginx/nginx.conf.template
- services/nginx/supervisor.conf
- tools/watch_logs.py
If `server.processes` is set to a number higher than 1,
run multiple Tornado servers via supervisord.
Each process runs on a separate port, and nginx directs requests
accordingly.  By default scheduling is round robin, but here we
selected scheduling by least number of active connections (see
https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/#choosing-a-load-balancing-method).
> Run multiple server processes via supervisord

- app/handlers/base.py
- app/psa.py
Currently, if a server gets re-deployed with a new database, previously
logged in users are able to access the system.  Often, their UIDs now
point to a new user, so they "log in" as this new person.
To address this, we now, in addition to user_id, set a cookie for OAuth
UID (Google email). When logging in, we check this cookie to
ensure that the user doesn't get logged into a different username.
The accompanying SkyPortal patch is https://github.com/skyportal/skyportal/pull/887
> Ensure OAuth UID matches username

- Makefile
- services/webpack/webpack.py
This doesn't fix any bug (everything was working as expected, as far as I can tell—no rebuilds on production runs); but it should help @dima in that now the bundle will rebuild (in production mode) upon initial app launch via `make run_production`.
> Always rebuild JS bundle upon launch

- app/test_util.py
(Elements can get hidden underneath a top bar, e.g.)
> Scroll elements to middle of viewport, not to top

- config.yaml.defaults
- services/external_logging/external_logging.py
- services/external_logging/supervisor.conf
- tools/watch_logs.py
This PR adds the capability of streaming a subset of logs to a 3rd party provider using `SysLogHandler` from the `logging` module of Python. Currently we use [papertrail](https://www.papertrail.com) which provides a free tier of 1-week log retention and alerting integration. External logging is established as a microservice. The (secret) parameters are set up in `config.yaml`:
```yaml
external_logging:
enabled: False
services:
papertrail:
enabled: False
url: logX.papertrailapp.com
port: XX
excluded_log_files: []
```
> Add external logging as a supervisord microservice

- services/external_logging/supervisor.conf
If there are no external services configured, the logging service should
exit immediately. That, in turn, should not be interpreted as a service
failure.
> Expect external logging to exit quickly under certain conditions

- services/external_logging/external_logging.py
- tools/watch_logs.py
We use a back-off strategy, starting with 1s and doubling the time
interval between checking until we only check once per minute.
> Detect log files to watch, even if they appear later

- services/app/app.py
Before, the app did these checks in the app_factory.  However, the
app_factory is sometimes used separately (in, e.g., documentation
build).  Now, we let the app_factory do its job: produce the app.
However, before letting the app listen on its port, we check in
with the migration manager.
> Handle migration manager checks in baselayer app service

- services/status_server/status_server.py
This avoids getting an HTTP 404 when loading routes other than `/`.  Also returns 503, so that clients don't think that SkyPortal is alive before it is.
> Status server returns 503 (temp unavail) and serves all routes

- services/nginx/nginx.conf.template
In our test case (SkyPortal), users often upload thumbnails on the
order of 20k to 40k; we're setting the upload buffer to 64k to
accommodate those.
For typical JSON bodies, these tend to land under 256k, so we provide
adequate buffer space for those too.
Responses should be a bit faster if they stay within buffer
limits (nothing gets buffered to disk then).
> nginx: tweak buffer sizes for common upload/download scenario

- app/test_util.py
This probably won't magically solve all the flakiness, but I think I found something that'll bring noticeable improvement.
- Move to an element after scrolling to it before attempting to click.
- Expose an option to have `scroll_to_element` scroll within the parent container instead of the window (this helps a lot with forms where we click an option from a long dropdown list). 
- Allow `StaleElementReferenceElement` to pass through the scripted clicking onto the ActionChains click attempt. I've noticed this error pop up occasionally on MUI components where the element comes up stale for some reason even though visually it is still there (specifically saw this today while looking at the classification delete button in `test_classifications`). 
I've tried out these changes locally and was …
> Robustify test_utils.py clicking

- app/test_util.py
This PR alters the `MyCustomWebDriver` class which is used in unit testing. It redirects the console logs from web browser instances driven by the driver to stdout, which is then rerouted to `geckodriver.log`. This allows access to the webdriver console from unit tests
> Redirect webdriven firefox console logs to geckodriver logs

- services/nginx/nginx.conf.template
We don't expect these servers ever to be down.  If they are, pinging
them once every 5s is not too much of a burden.  This also allows for
more rapid recovery once they become available.
> Lower timeout from 10s to 5s

- app/models.py
Currently we use the adjective `owned` throughout the codebase to indicate that a user has read access to a database record. This is a bit confusing as `owned` now has a precise meaning - that a user was the one who created a record. This PR replaces `owned` -> `readable` throughout the code base to make this distinction.
> rename owned -> readable

- app/model_util.py
- services/app/app.py
- services/migration_manager/migration_manager.py
This is needed to support migrations.
> By default, do not create tables if tables already exist

- app/config.py
- requirements.txt
This PR addresses the issue where a local config.yaml falls behind config.yaml.defaults, leading to missing front-end route mappings, causing critical failures.
Closes https://github.com/skyportal/skyportal/issues/1531
> Ensure config.yaml app.routes matches that of config.yaml.defaults (in parent app)

- app/config.py
- requirements.txt
- services/template_watch/supervisor.conf
- services/template_watch/template_watch.py
- tools/fill_conf_values.py
I sometimes forget that `.template` files aren't compiled automatically, prompting investigation into why changes aren't propagated.
This PR introduces a file monitor, that compiles templates when they are modified, which in turn triggers webpack (in the case of JavaScript).
> Monitor template files

- tools/junitxml_report.py
This should address the failures we've been seeing in log parsing on CI.
> junitxml_report: derive filename from classname

- services/webpack/supervisor.conf
Otherwise, webpack leaves a node server running for about 40 seconds
> Shut down all webpack processes

- app/handlers/base.py
When we start the app, a bunch of mapped objects are loaded into the database session (ACLs, admin users, etc.), which then stay in the session during the first API handler call on each web worker. When `verify_permissions` is first called, it checks permissions on everything in the session, which includes the stale references from app startup. Sometimes, the first API call can throw a permission error if we try to check the permissions of a stale object that is irrelevant to the current transaction but has just stayed in the app from app startup. This PR modifies the base handler to clear the database session at the beginning of each api handler call, ensuring that objects in the database session are only relevant to the API call (and thus any permissions errors that are thrown are …
> clear the sqlalchemy session at the beginning of each api handler call

- app/handlers/base.py
- app/models.py
- config.yaml.defaults
This PR contains three improvements around security. 
1. I added a Security section to `config.defaults.yaml`. This allows users to enable or disable "strict" mode. When strict is on, any illegal access detected by `self.verify_permissions()` is raised as an exception. Otherwise, it is simply issued as a warning. I also added an option to send security reports to a webhook channel (i.e., slack) in strict or non-strict mode. 
2. I augmented the error messages sent to the slack channel with a full traceback to show what handler a particular access violation occurred in. 
3. I vectorized the security checks within `self.verify_permissions()`. Previously, each record would issue a separate database query for permissions checks. Although each check was fast on its own (~0.5ms), for  pages with …
> Security Improvements

- app/handlers/base.py
- app/models.py
This pr eliminates the use of `Base.query.get(pk_set)` in the bulk permissions checker, which was causing errors to raise for pk_sets with a cardinality greater than 1.
> fix bulk permissions checker

- app/models.py
Current queries that are slow on SkyPortal have access policies that are instances of `AccessibleIfRelatedRowsAreAccessible(public_relationship=access_mode)`, that is to say, anything that requires the ability to access a related record that itself has a public access policy. 
The reason this is slow is because joining against publicly accessible records renders the entire ID column of the associated table as a subquery, which is slow. In reality, this join doesn't need to be performed, as it does not filter the output of the calling join in any way. 
Example:
This query for accessible annotations is currently slow. The associated policy is:
```python
read = accessible_by_groups_members & AccessibleIfRelatedRowsAreAccessible(
obj='read'
)
```
This is the resulting query:
```SQL
fritz-1=> …
```
> dont explicitly join on tables that are access=Public

- app/models.py
This needs to be followed up with a change to SkyPortal, where the connections are bumped up to 10 + 10 (instead of 5 + 10, as it is now).
> Make database engine creation defaults adjustable.

- app/models.py
This PR simplifies the permissions querying for system admins for the baselayer-provided permission rule classes. Specifically, all rows are just returned if the user is a system admin without doing any of the normal checks when using the `AccessibleIfRelatedRowsAreAccessible` and `ComposedAccessControl` classes. This reflects the same approach already used in `AccessibleIfUserMatches`. 
For example, if you have a rule that is the AND of two rules, the `ComposedAccessControl` as is will join the entire table in question to itself since both pieces of the permission rule will return all rows for a system admin. Now, we'll just return the table once.
> Simplify access controls for system admins

- app/models.py
This is the implicit default behavior when `id` is a single-column primary key, but `autoincrement=True` must be set explicitly when the `id` column is used as a part of a multiple-column primary key. This allows subclassed models to specify additional columns as part of the primary key. 
https://docs.sqlalchemy.org/en/14/core/metadata.html?highlight=autoincrement#sqlalchemy.schema.Column.params.autoincrement
> Explicitly set BaseMixin id to autoincrement

- app/access.py
- app/models.py
Also changed the `is_active` function for Users, which currently is just returning `True` no matter what, so that it serves as a check for expired users. We don't seem to be using this function anywhere, but doesn't hurt to have it be more of a real function in case we use it later. This will be accompanied by a PR on SkyPortal to actually use the new column for user expiration functionality (setting expired users to view only automatically). Part of addressing fritz-marshal/fritz#180
Plus black formatting.
> Add expiration_date to Users

- services/nginx/nginx.conf.template
Log messages will now be of the form `127.0.0.1 - - [token e7a82026] [20/Jul/2021:14:59:50 -0700] "GET /api/sysin HTTP/1.1" 400 110 "-" "python-requests/2.25.1"`
> Include truncated http_authorization in nginx log messages

- app/models.py
Re-opening as this is needed to address a bug when calling `get_if_accessible_by` w/ `raise_if_none=True` for some models.
> Update record accessibility check

- services/app/app.py
We may still need to provide trusted IPs for our load balancers in
order to get the user IP, as described in the last paragraph below.
From the Tornado docs (https://www.tornadoweb.org/en/stable/httpserver.html):
> If xheaders is True, we support the X-Real-Ip/X-Forwarded-For and
X-Scheme/X-Forwarded-Proto headers, which override the remote IP and
URI scheme/protocol for all requests. These headers are useful when
running Tornado behind a reverse proxy or load balancer. The
protocol argument can also be set to https if Tornado is run behind
an SSL-decoding proxy that does not set one of the supported
xheaders.
>
> By default, when parsing the X-Forwarded-For header, Tornado will
select the last (i.e., the closest) address on the list of hosts as
the remote host IP address. To select the …
> Pass originating IP through to app

- requirements.txt
The currently pinned version 3.3.3 is causing trouble with OAuth: users cannot log into Fritz.
Was able to reproduce on staging F, Installed 4.1.0, issue apparently resolved.
> Up social-auth-core version to 4.1.0

- services/nginx/nginx.conf.template
- Initially, we set the value to `tcp_nodelay` in this patch.  But the
issue is sufficiently complex that I am punting to the nginx default
(`on`, as it happens).
As John Nagle, the author of the Nagle algorithm, says at
https://news.ycombinator.com/item?id=9048947:
"The real problem is ACK delays. The 200ms "ACK delay" timer is a
bad idea that someone at Berkeley stuck into BSD around 1985 because
they didn't really understand the problem. A delayed ACK is a bet
that there will be a reply from the application level within
200ms. TCP continues to use delayed ACKs even if it's losing that
bet every time."
A detailed explanation of the issue is given at
https://eklitzke.org/the-caveats-of-tcp-nodelay
- Set `tcp_nopush` to on.  This allows combination of the response
header and the beginning …
> Tweak nginx configuration for performance

- services/nginx/nginx.conf.template
Otherwise, CSS will not load, e.g.
> Serve static files with correct MIME types

- doc/setup.md
I found out the hard way that you have to install nginx with the `+realip` variant. See skyportal/skyportal#2292.
> Add system dependency instructions for MacPorts

- tools/db_init.py
On some platforms, commonly Docker containers, sudo is missing.  Don't
try to invoke it if we can't find it.
Closes https://github.com/skyportal/skyportal/issues/968
> db_init: detect when sudo is available

- app/models.py
This patch removes the table-wide unique constraint on
Token.name, and instead adds a new (user_id, token_name)
unique constraint so that different users can have tokens
of the same name.
This will require a migration when upgrading SkyPortal.
Closes https://github.com/skyportal/skyportal/issues/2195
> Add (user_id, name) Token unique constraint

- tools/db_init.py
Previously, we used dropdb, createdb, and createuser, but these
commands operate on the local database, and thus is not suitable for
working in a Docker container network.
> Use psql for all database operations

- services/migration_manager/migration_manager.py
Requires the following patch to skyportal once merged:
```diff
-    # If tables are found in the database, new tables will only be added
-    # in debug mode.  In production, we leave the tables alone, since
-    # migrations might be used.
-    create_tables(add=env.debug)
model_util.refresh_enums()
```
Follows up on https://github.com/skyportal/skyportal/pull/2564 and closes https://github.com/skyportal/skyportal/issues/1802
> Refresh tables using migration manager

- app/models.py
- requirements.txt
Allows the permissions checking to pass in sqlalchemy >= 1.4.
See: https://docs.sqlalchemy.org/en/14/changelog/migration_14.html
in particular: Built-in FROM linting will warn for any potential cartesian products in a SELECT statement
> Aliasing like that does not work for sqlalchemy >= 1.4

- app/models.py
SQLA1.4 fix to return SQLA1.3-style aliased entity, following a fix suggested in @dannygoldstein's issue (https://github.com/sqlalchemy/sqlalchemy/issues/7576)
> use safe_aliased fix

- tools/db_init.py
Often, in production, this database does not exist
> db_init: don't abort if we cannot connect to the test database

- app/config.py
- requirements.txt
Before, we forced config.yaml to reflect the routes in
config.yaml.default.  However, users may want to add or remove
routes by specifying a new routes key entry.
> No longer enforce a route structure on the config file

- services/nginx/nginx.conf.template
Specifically:
- duplicate MIME type "text/html" in ./baselayer/services/nginx/nginx.conf:20
- could not build optimal types_hash, you should increase either types_hash_max_size: 1024 or types_hash_bucket_size: 64; ignoring types_hash_bucket_size
> Change config to avoid nginx warnings

- services/webpack/webpack.py
Often, production images ship without node_modules, so this would
re-download all npm dependencies.
Production bundles should be built as part of docker images instead.
> Do not run webpack on production builds

- services/nginx/nginx.conf.template
This is done when the "Accept-Encoding: gzip" header is present, which
seems to be the case for `fetch` API requests.
> Compress application/json responses

- app/handlers/base.py
- app/models.py
This PR begins to move the permissions infrastructure to use sqlalchemy's select instead of query.
> Use select instead of query for sqlalchemy

- Makefile
Since we cannot specify arguments to make targets easily, we simply print the
command the user should execute.
Closes gh-264
> Update `make attach` for multiple processes

- tools/check_js_deps.sh
Skyportal relies on baselayer, but has dependencies requiring both react v16 and v17 (see Issue https://github.com/skyportal/skyportal/issues/2656). Though ideally all deprecated React dependencies would be eliminated, this PR would in the interim allow both versions to be used concurrently.
> Add '--legacy-peer-deps' flag for npm install

- app/handlers/base.py
- app/models.py
his PR introduces scoped sessions with user access verification.
It also introduces new methods on the Base model, to allow querying using the new "select" style compatible with SQLA 2.0
It also fixes the behavior of `get_if_accessible_by` to respond exactly the same if the row requested does not exist or if it is not accessible. 
This is mostly backward compatible, but a separate PR to skyportal fixes the few issues in the handlers and the tests that are broken by this change. 
Most importantly, it allows us to move each handler separately into the new SQLA 2.0 style without having to change everything at once.
> Select statements and Session

- services/cron/cron.py
- tools/test_frontend.py
- Relied on `cfg['missing_key']` returning None; that behavior has
been changed to be consistent with the Python dict
- Microservice error report was incorrectly passed to string formatter
> Fix baselayer tests

- tools/test_frontend.py
Allow the app longer time to come up. Also wait until supervisord.conf is built before polling supervisor status (avoids complaining about conf not found)
> allow longer for app to boot up in  `test_frontend `

- services/status_server/status_server.py
This PR modifies status_server to return 200's instead of 503's based on the GCP warnings: "Unhealthy
Readiness probe failed: HTTP probe failed with statuscode: 503".
> Have status_server return 200 when starting

- app/model_util.py
- app/models.py
This PR is part of an effort to silence (but not fix) the SQLA warnings we have on relationships. 
I've allowed passing the `overlaps` argument to be added to each relationship that is defined inside `app.models.join_model`. 
This makes it possible to silence warnings, although a more serious investigation should be made into the root cause of the warnings. 
I've also allowed passing `new_name` as an argument that allows defining the relationship model's name, instead of the default which is just the mashup of the two model names. This removes warnings where multiple mappers have the same name. 
Finally, I've also made the output of `app.model_util.create_tables` be more compact. 
This, in combination with a skyportal PR will make the outputs much shorter.
> Allow overlaps in join_model

- services/status_server/status_server.py
Revert the status code 200 back to 503 in `status_server`. 
This solves the problem that some of the tests cannot start on CI.
> Revert changes in status_server

- services/nginx/nginx.conf.template
This PR adds request_length to nginx log, which should allow us to track query sizes by IP. See e.g. https://www.ruby-forum.com/t/logging-variables-bytes-sent-where-is-bytes-read/241597/8.
> Add request_length to nginx log

- services/cron/cron.py
skips over jobs that are in the config but missing key parameters.
> cron: do not fail if a job entry is empty

- config.yaml.defaults
- services/nginx/nginx.conf.template
This PR allows us to modify the max request body size from the config file of the baselayer.
This is needed in some instances of SkyPortal where we need to upload .fits file (for analysis, or as comment attachments).
Of course, after a first review to figure out if anything should be done differently, it will be followed by an associated PR on SkyPortal main.
> Modify Nginx max request body size (from client) in the config

- .pre-commit-config.yaml
- requirements.txt
This PR removes a double requirement for `selenium-requests`, keeping the newer version.
> Fix double selenium-requests requirement

- app/json_util.py
This PR adds a kwargs to to_json, useful for using to_json as a drop-in replacement for json.dumps (which it is, but will benefit from taking the various optional args).
> Add kwargs to to_json

- .github/workflows/test.yaml
- app/test_util.py
- requirements.txt
This PR adds webdriver-manager to deal with GeckoDriver (see https://stackoverflow.com/questions/46753393/how-to-run-headless-firefox-with-selenium-in-python, as my upgrade to Sonoma broke it).
> webdriver-manager

- Makefile
- requirements.txt
- tools/check_app_environment.py
An attempt/suggestion to fix https://github.com/cesium-ml/baselayer/issues/374
ALSO: we try migrating to pre-commit.ci now that the pre-commit github action is deprecated.
> Install packaging first separately

- static/js/components/Notifications.jsx
Some of SkyPortal tests are flaky and/or require extra retry logic because some of the baselayer <Notification> appear on top of elements we are trying to click. A good example is the weather widget, which during testing might request for a telescope fixture that has been deleted. That yields an error that displays as a notification. But for some tests like the dashboard or quick search bar, this notification overlaps with things we want to click. So the click happens, but clicks on the notification and that breaks the rest of the test.
A simple way to figure out if these notifications are there so that we can make them go away is to give them a data-testid that contains `notification` in it.
This PR does just that.
> Notification data-testid

- config.yaml.defaults
- services/nginx/nginx.conf.template
The current configuration is incorrect. In the app, the `ssl` key of the config is used to figure out if the server should be accessed with https (if True) or http (if False), and not whether or not nginx should use an SSL certificate. For that, we have the `use_ssl_certificate` key already present in the default config.
> Nginx conf: list <server> SSL only if a certificate is used

- app/models.py
The idea of this PR is to add a bio field to the user model, as well as a bot flag (maybe should be renamed to `is_bot` to make the boolean-ness more obvious where we use it???).
it's nice in general to have a field for a user to store a bio that other users could access, and this will come in handy for a couple of applications:
- we're considering a public user profile page, where other users that are in any of your groups (except public of course, as all users are there) can see your user profile's most basic info, as well as some kind of activity tracker similar to the news feed but only for a given user.
- for the TNS reporting, before we can let bot accounts report to the Transient Name Server autonomously (needed for BTSbot), we need to be able to mark bot accounts as such (hence …
> User: bio and bot flag

- .github/workflows/test.yaml
- app/test_util.py
This PR checks for geckodriver binary before bothering to install it and avoids some requests that seem to be overwhelming the GA.
> check for geckodriver binary before bothering to install it

- .github/workflows/docs.yaml
- .github/workflows/test.yaml
- app/access.py
add an __authenticated__=True attribute to handler methods that require auth, so we can use it when autogenerating the openapi specs and show/hide token auth headers in the auto-generated code examples.
Required for us to then merge https://github.com/skyportal/skyportal/pull/5273
> auth_or_token decorator: set __authenticated__=True attribute

- app/access.py
add a __permissions__ attr to the handlers we wrap in the `@permissions([...])` decorator, so that on import (of the decorated methods) we can easily figure out what permissions an endpoint might need.
Will come in handy when skyportal auto generates the open API specifications, so we can inject a list of required permissions to be displayed in the API docs
> @permissions decorated handlers: add a __permissions__ attr
