app/flow.py, app/handlers/base.py, app/handlers/socket_auth.py, services/websocket_server.py, static/js/MessageHandler.js
BaseHandler now has `push_all`, which sends WebSocket messages to all
connected frontends.  You can also use `push(user, action, payload)`
with user `*` to achieve the same effect.
=> Add websocket multicast

app/flow.py, app/handlers/base.py, app/models.py, conf/nginx.conf.template, conf/supervisor/supervisor.conf.template, config.yaml.example, services/app.py, services/fake_oauth2.py, services/message_proxy.py, services/websocket_server.py, tools/fill_conf_values.py
Re-open @acrellin's PR https://github.com/cesium-ml/baselayer/pull/18
=> Parameterize ports

tools/makefile_to_help.py
- Add support for dashes in targets
- Automatically determine width of target column
=> Simply Makefile to help script.

services/app.py
Commented out sql query logging (can be restored if needed)
=> Reduce SQL query logging

app/config.py, app/env.py, tools/env_summary.py
Continuation of https://github.com/cesium-ml/baselayer/pull/56/files to address https://github.com/skyportal/skyportal/issues/69, warning about usage of default configs.
=> Warn about using default configs, allow missing configs

app/config.py
Will close https://github.com/skyportal/skyportal/issues/229 as soon as baselayer is updated for SkyPortal.
=> Allow config file from directory outside app

app/config.py, conf/nginx.conf.template, conf/supervisor/supervisor.conf.template, config.yaml.defaults, tools/fill_conf_values.py
Closes https://github.com/skyportal/skyportal/issues/245 and potentially https://github.com/skyportal/skyportal/issues/164
=> Allow disabling dask through configuration

Makefile, doc/extending.md, doc/index.rst, doc/setup.md, doc/usage.md
Also add documentation to explain this feature.
=> Run templating on files in parent directory too

app/models.py
Fixes https://github.com/skyportal/skyportal/issues/471
=> make created_at and modified default in the same way

app/handlers/base.py, app/models.py
The previous relationship was causing sqlalchemy to error upon attempting to delete a user.
=> Remove buggy User.acls relationship and use hybrid property instead

app/models.py, requirements.txt
This PR documents the `EXECUTEMANY_PAGESIZE` parameter introduced in #106 within the codebase.
=> Document `EXECUTEMANY_PAGESIZE`

app/handlers/base.py
This should make it possible to track down where errors occur
=> Include route in error messages

app/models.py, requirements.txt
This PR adds basic information, like name, contact email, etc. to the User model. This will be heavily used upcoming Skyportal PRs.
=> Update User model

app/config.py, app/flow.py, services/message_proxy/message_proxy.py, services/webpack/webpack.py, services/websocket_server/websocket_server.py
Some were still using print statements
=> Use logging to timestamp all log entries

app/test_util.py
@acrellin Some suggested CSS selector additions to our driver test functions.  Let me know what you think.
=> Add CSS variants of XPATH selectors

app/models.py
This PR documents each class in `baselayer.app.models`. The methods, relationships, properties, and `Column`s of each documented class are also documented.
=> Document models

app/models.py
This should fix the issue where a secure site complains about getting insecure content.
=> secure gravatar URL

app/flow.py, app/handlers/base.py, app/handlers/socket_auth.py, services/websocket_server/websocket_server.py
Closes https://github.com/skyportal/skyportal/issues/830
=> User user_id instead of username as constant identifier for websocket auth

Makefile
Put `@export FLAGS="$(FLAGS)" && \` (back) into `run_production` Makefile target, because without it `make run_production` fails on Docker.
=> fix make_production

app/json_util.py
Add JSON serialization support for phone numbers from sqlalchemy_utils phone numbers
=> Serialize PhoneNumber types from SQLAlchemy utils

config.yaml.defaults, services/migration_manager/migration_manager.py, services/migration_manager/supervisor.conf, services/nginx/nginx.conf.template, services/status_server/status_server.py, services/status_server/supervisor.conf
The migration manager checks to see whether migrations are present.
If so, it attempts to perform a migration if the DB is not up to date
already.  It then runs an HTTP server to report the current migration
status.
This status can be queried by the app factory to decide whether to
launch or not.
See also https://github.com/skyportal/skyportal/pull/1055
=> Migration manager

Makefile, tools/junitxml_report.py, tools/test_frontend.py
=> Parse JUnitXML to generate more actionable test failure reports

tools/fill_conf_values.py
=> Allow jinja2 template inheritance

Makefile
Closes https://github.com/cesium-ml/baselayer/issues/161
=> Report flags correctly

Makefile, conf/supervisor/supervisor.conf.template
Also disable logging to stdout, otherwise it appears mixed in with app output
=> Enable more verbose logging for supervisor

services/status_server/status_server.py
Partially addresses https://github.com/skyportal/skyportal/issues/1344
=> Serve valid 502s on API requests

tools/fill_conf_values.py
Needed to add the version to the JS bundle
=> Add custom jinja filters

app/handlers/base.py, services/nginx/nginx.conf.template
Closes https://github.com/skyportal/skyportal/issues/1164
=> Do not log 404s from HEAD requests

app/handlers/base.py, app/models.py
To be used as the default method for closing out database transactions.
=> Add `verify_and_commit()` method to `BaseHandler`

app/handlers/base.py
this pr moves the anti join for the bulk permission check from the python to sql, causing only the inaccessible IDs to be sent back over the network, instead of the accessible ids. In general, the inaccessible IDs should be a much smaller list than the accessible IDs, so this should further improve the efficiency of the bulk record check.
=> minimize data transferred over network in bulk permission check

app/models.py
This PR is essentially a follow-up to Danny's PR #221. It reinforces the reasoning behind the changes there.  Most of these changes are just from black formatting, the relevant changes are lines 480:482 and 587:591 (I'll highlight these in a comment).
Basically, in #221, the "ignore and continue if combining a `Public` attribute" logic was added after the `class_attribute` for said attribute was already joined into the query ([here](https://github.com/cesium-ml/baselayer/blob/be52c9e6c8a74096e2ff154d0067f152e0c74aa8/app/models.py#L466)) so queries were still joining those in. The changes in lines 480:482 addresses this, and is responsible for the sample effects I'll describe below. 
This came up in the query for accessible Classifications on a particular Obj, generated …
=> Properly ignore joins on Public attributes

config.yaml.defaults
Also change the default of `processes` to 4 and `dedicated_frontend_processes` to 2.
=> Add documentation for `processes` and `ssl` options

tools/pip_install_requirements.py
We are currently using `pkg_resources.require` to ensure that
dependencies are met.  However, and perhaps recently, this function
only checks that the dependencies can be resolve, *not that it is
resolved by the currently installed distribution*. We switch to
`pkg_resources.working_set.resolve` which does exactly that.
If requirements are not met, we call pip to install the missing
packages. Before, that was done on each `requirements.txt` file
separately, which does not ensure that the joint set of dependencies
is met.  This is fixed by calling `pip` with multiple `-r
requirements_file` arguments.
Before, when there were version conflicts in the requirements
specification, we called pip to try and resolve it.  My understanding
is that this is a fatal error (e.g., requiring `requests<25` …
=> Satisfy joint dependencies between all requirement.txt files

app/handlers/base.py
Currently we return HTTP 400 (Bad Request), which does not match an authorization failure.
=> Return HTTP 401 (Unauthorized) if token authentication fails

app/test_util.py
This PR uses RequestsSessionMixin, an updated class of Selenium Requests.
=> RequestsSessionMixin

tools/check_app_environment.py
Closes https://github.com/skyportal/skyportal/issues/2599
=> Update minimum requirements for node (17.3.0) and npm (8.3.2)

.github/workflows/test.yaml, .pre-commit-config.yaml
Closes https://github.com/cesium-ml/baselayer/issues/295
=> Add pre-commit checks

app/handlers/base.py
Improve logging by suppressing full prints of expected exceptions.
=> Ignore certain classes of exceptions

app/models.py
https://docs.sqlalchemy.org/en/14/orm/session_api.html#sqlalchemy.orm.Session.params.future
https://docs.sqlalchemy.org/en/14/orm/session_api.html#sqlalchemy.orm.Session.rollback
=> Ensure that nested sessions are unrolled, rolled back, and closed.

.flake8, .pep8speaks.yml, app/handlers/base.py, app/models.py
This PR reverts the changes in #293
=> Revert #293

services/app/app.py, services/nginx/nginx.conf.template, tools/fill_conf_values.py
=> Only listen on localhost in debug mode

doc/setup.md
Fix #283 , by providing instructions on how to modify the baselayer port.
=> Info on changing baselayer app port

app/config.py
@Theodlz This should make your life a bit simpler in your default roles PR.
Now you can do `cfg.get('user.default_roles', [])`
=> Add  method for Config

app/access.py, app/handlers/base.py, app/models.py, doc/dev.md, tools/db_init.py
While running tests on skyportal with the new SQLA 2.0 tools, I ran into some more bugs. This tries to fix those, together with running the entire SP test suite (in a separate PR for SP).
=> More upgrades to session

app/models.py
This PR adds affiliations to the user model. The affiliations are stored as a list of strings, which can be displayed on the frontend and used to write scientific papers or circulars for example. 
A WIP PR on SkyPortal : https://github.com/skyportal/skyportal/pull/3092 uses this to display it on the frontend.
=> User model - Affiliations

services/nginx/nginx.conf.template
This PR increases the nginx timeout to try to improve app responsivity.
=> Try increasing nginx timeout a bit

requirements.txt
This PR updates the selenium requirements post-Opera deprecation.
=> Update selenium requirements

services/nginx/nginx.conf.template
This PR extends the nginx timeout further to see if it improves responsivity (or not).
=> Extend timeout some more to see if it makes a difference on production

.github/workflows/test.yaml, app/test_util.py
Made the timeout on the login test longer (5s -> 20s).
=> Fix baselayer tests

.github/workflows/lint.yaml, .github/workflows/test.yaml, tools/check_app_environment.py
Bumps node to 18 instead of 17. Also fixes the GHA to always test against the baselayer app. Also, splits out the linter into a separate test.
=> Bump node to 18 and fix GHA

app/handlers/base.py, app/model_util.py, app/models.py, requirements.txt
This PR updates SQLAlchemy to 2.0.
=> SQLAlchemy 2.0

.pre-commit-config.yaml, app/models.py
This PR moves declarative_base import to sqla 2.0 place.
=> declarative_base import

config.yaml.defaults, services/nginx/nginx.conf.template
This PR makes the nginx fail_timeout variable settable from the config.
=> fail_timeout

app/app_server.py, config.yaml.defaults
This PR adds a timeout for social auth.
=> social auth timeout

app/handlers/base.py
adds on top of what has been added in https://github.com/cesium-ml/baselayer/pull/354 already
=> Social core - catch DBSession errors to proceed with social_core's auth pipeline

app/models.py
Associated SP PR: https://github.com/skyportal/skyportal/pull/4024
=> Missing SQLAlchemy2 syntax 

tools/pip_install_requirements.py
This PR allows for dependencies on github branches, a la git+https://github.com/sncosmo/sncosmo.git@master#egg=sncosmo.
=> Allow for github dependencies

app/models.py, config.yaml.defaults
This PR adds a config flag for turning on (or off) database logging.
=> Database logging

config.yaml.defaults, services/nginx/nginx.conf.template
This PR makes it possible to set set ssl certificates from the config (to ease updating the code when you modify this file).
=> Set ssl certificates from config

.github/workflows/docs.yaml, .github/workflows/lint.yaml, .github/workflows/test.yaml, .pre-commit-config.yaml, Makefile, app/config.py, app/models.py, app/test_util.py, config.yaml.defaults, doc/setup.md, services/dask/supervisor.conf.template, services/external_logging/external_logging.py, services/status_server/status_server.py, services/websocket_server/websocket_server.py, static/js/API.js, static/js/components/Notifications.jsx, static/js/components/WebSocket.jsx, static/js/reconnecting-websocket.js, tools/check_app_environment.py, tools/check_js_deps.sh, tools/db_init.py, tools/junitxml_report.py, tools/makefile_to_help.py, tools/test_frontend.py
Just a PR to get the GAs to run and try to fix them. Will commit anything back to @stefanv's PR if successful
=> Refresh 2023-12 - debug

doc/setup.md
Not sure it's in the right spot, but it should be *somewhere*.
=> Document debug mode

tools/pip_install_requirements.py
It's not perfect; in the long run we may want to use a tool like uv or pixi instead.
=> Replace pkg_resources with packaging & importlib

requirements.txt
Addresses https://github.com/sqlalchemy/sqlalchemy/issues/11334
=> Update SQLAlchemy to avoid CI error (https://github.com/sqlalchemy/sqlalchemy/issues/11334)
